# Generated by Django 4.1.7 on 2023-03-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_jobprofile_language_skillset_userprofile_job_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
