# Generated by Django 4.1.7 on 2023-03-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(to='land.language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='land.skillset'),
        ),
    ]
