# Generated by Django 4.1.7 on 2023-03-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_alter_userprofile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(to='land.language'),
        ),
    ]
